language: php

php:
    - 7.2
    - 7.3
    - 7.4

before_install:
    - composer self-update
    - composer --version
    - if [ "$TRAVIS_PHP_VERSION" == "7.2" ]; then wget http://get.sensiolabs.org/php-cs-fixer-v2.phar; fi
    - if [ "$TRAVIS_PHP_VERSION" == "7.2" ]; then php php-cs-fixer-v2.phar --version; fi


install:
    - COMPOSER_ROOT_VERSION=dev-master composer update --prefer-source $COMPOSER_FLAGS

script:
    - bin/phpunit
    - if [ "$TRAVIS_PHP_VERSION" == "7.2" ]; then php php-cs-fixer-v2.phar fix --dry-run -v; fi

