language: php

php:
    - 7.2
    - 7.3
    - 7.4

before_install:
    - composer self-update
    - composer --version

install:
    - COMPOSER_ROOT_VERSION=dev-master composer update --prefer-source $COMPOSER_FLAGS

script:
    - bin/phpunit
